substitutions:
  _SERVICE_NAME: exf-app-staging
  _REGION: us-central1
  _ALLOW_UNAUTH: "false"

options:
  logging: CLOUD_LOGGING_ONLY

steps:
  - name: gcr.io/cloud-builders/docker
    id: build-image
    args:
      ["build","-t","us-central1-docker.pkg.dev/$PROJECT_ID/exf-repo/exf-app:$COMMIT_SHA","."]

  - name: gcr.io/cloud-builders/docker
    id: push-image
    args:
      ["push","us-central1-docker.pkg.dev/$PROJECT_ID/exf-repo/exf-app:$COMMIT_SHA"]

  - name: gcr.io/google.com/cloudsdktool/cloud-sdk:slim
    id: deploy-service
    entrypoint: bash
    args:
      - -c
      - |
        set -euo pipefail
        IMAGE="us-central1-docker.pkg.dev/${PROJECT_ID}/exf-repo/exf-app:$COMMIT_SHA"
        if [[ "${_ALLOW_UNAUTH}" == "true" ]]; then
          AUTH_FLAG="--allow-unauthenticated"
        else
          AUTH_FLAG="--no-allow-unauthenticated"
        fi
        gcloud run deploy "${_SERVICE_NAME}" \
          --image "$$IMAGE" \
          --region "${_REGION}" \
          $${AUTH_FLAG} \
          --no-traffic
        gcloud run services update-traffic "${_SERVICE_NAME}" \
          --region "${_REGION}" --to-latest

  - name: gcr.io/google.com/cloudsdktool/cloud-sdk:slim
    id: smoke-test
    entrypoint: bash
    args:
      - -c
      - |
        set -euo pipefail
        SERVICE_URL=$(gcloud run services describe "${_SERVICE_NAME}" --region "${_REGION}" --format='value(status.url)')
        for i in {1..60}; do
          READY=$(gcloud run services describe "${_SERVICE_NAME}" \
            --region "${_REGION}" \
            --format='value(status.conditions[-1].status)')
          if [[ "$$READY" == "True" ]]; then
            echo "Service ${_SERVICE_NAME} is Ready"
            exit 0
          fi
          echo "Waiting for ${_SERVICE_NAME} to become ready (attempt $$i)"
          sleep 5
        done
        echo "Service ${_SERVICE_NAME} not ready after waiting"
        exit 1

images:
  - us-central1-docker.pkg.dev/$PROJECT_ID/exf-repo/exf-app:$COMMIT_SHA
